"""Model config definitions for each prediction target - features, hyperparameters, and evaluation settings."""

# XGBoost regressor predicting race finish position (1-20) - quali_position feature uses actual qualifying position at training time
FINISH_POSITION_MODEL = {
    "name": "finish_position",
    "target": "finish_position",
    "model_type": "XGBRegressor",
    "features": [
        "rolling_quali_pos_last_3",
        "rolling_quali_pos_last_5",
        "rolling_finish_pos_last_3",
        "rolling_finish_pos_last_5",
        "rolling_crash_dnf_rate_last_5",
        "circuit_rolling_quali_pos_last_3",
        "circuit_rolling_quali_pos_last_5",
        "circuit_rolling_finish_pos_last_3",
        "circuit_rolling_finish_pos_last_5",
        "season_points_to_date",
        "driver_overtake_index",
        "round_number",
        "constructor_rolling_mechanical_dnf_rate_last_5",
        "constructor_rolling_quali_pos_last_3",
        "constructor_rolling_finish_pos_last_3",
        "constructor_rolling_finish_pos_last_5",
        "constructor_form_trend_last_5",
        "driver_race_elo",
        "constructor_race_elo",
        "predicted_quali_position",
        "sprint_quali_position",
        "circuit_overtake_index",
        "circuit_pole_to_win_rate",
        "circuit_top3_grid_to_podium_rate",
        "circuit_dnf_rate",
        "circuit_sc_vsc_rate",
        "fp2_gap_to_leader_pct",
        "fp3_gap_to_leader_pct",
        "fp3_sector1_gap_to_leader_pct",
        "fp3_sector2_gap_to_leader_pct",
        "fp3_sector3_gap_to_leader_pct",
        "fp3_teammate_gap_pct",
        "fp2_longrun_avg_gap_to_field_pct",
        "fp2_laps_completed",
    ],
    "hyperparams": {
        "n_estimators": 200,
        "max_depth": 4,
        "learning_rate": 0.05,
        "subsample": 0.6,
        "colsample_bytree": 0.7,
        "min_child_weight": 1,
        "random_state": 42,
        "early_stopping_rounds": 20,
    },
    "eval_metrics": ["mae", "spearman"],
    "feature_importance_top_n": 10,
}


# XGBoost regressor predicting qualifying position (1-20) - no quali input by design, only pre-session features
QUALI_POSITION_MODEL = {
    "name": "quali_position",
    "target": "quali_position",
    "model_type": "XGBRegressor",
    "features": [
        "rolling_finish_pos_last_3",
        "rolling_finish_pos_last_5",
        "rolling_quali_pos_last_3",
        "rolling_quali_pos_last_5",
        "circuit_rolling_quali_pos_last_3",
        "circuit_rolling_quali_pos_last_5",
        "season_points_to_date",
        "round_number",
        "constructor_rolling_quali_pos_last_3",
        "constructor_rolling_finish_pos_last_3",
        "constructor_rolling_finish_pos_last_5",
        "constructor_form_trend_last_5",
        "driver_quali_elo",
        "constructor_quali_elo",
        "circuit_data_n_seasons",
        "circuit_fp3_top3_to_quali_top3_rate",
        "fp2_gap_to_leader_pct",
        "fp3_gap_to_leader_pct",
        "fp3_sector1_gap_to_leader_pct",
        "fp3_sector2_gap_to_leader_pct",
        "fp3_sector3_gap_to_leader_pct",
        "fp3_teammate_gap_pct",
        "fp2_longrun_avg_gap_to_field_pct",
        "fp2_laps_completed",
        "sprint_quali_position",
    ],
    "hyperparams": {
        "n_estimators": 200,
        "max_depth": 4,
        "learning_rate": 0.1,
        "subsample": 0.9,
        "colsample_bytree": 0.7,
        "min_child_weight": 10,
        "random_state": 42,
        "early_stopping_rounds": 20,
    },
    "eval_metrics": ["mae", "spearman"],
    "feature_importance_top_n": 10,
}